<!-- "follow_mass_page": {
    "vintie_followers_title": "Abonnés Vintie",
    "followings": "Abonnements",
    "followers": "Abonnés",
    "folowings_desc": "Abonnez-vous aux mêmes personnes que l'utilisateur",
    "followers_desc": "Abonnez-vous aux abonnés de l'utilisateur sélectionné",
    "url_entry_desc": "Entrez l'URL du compte utilisateur",
    "scrap_btn": "SCRAP",
    "follow_title": "Follow",
    "unfollow_title": "Unfollow",
    "desc_1": "Abonnez-vous rapidement à de nombreuses personnes",
    "desc_2": "Désabonnez-vous en un clic de tous les comptes pour ne plus être dérangé par les notifications",
    "follow_btn": "FOLLOW",
    "recover_btn": "RECOVER",
    "settings_title": "Paramètres",
    "tree_btn": "Tree",
    "tree_desc": "Suivez le dernier compte avec lequel vous avez effectué une transaction, puis ses abonnés, et ainsi de suite, jusqu'à atteindre le nombre d'abonnements souhaité",
    "my_reviews_btn": "Mes avis",
    "my_reviews_desc": "Suivez tous les comptes avec lesquels vous avez eu une transaction",
    "nb_ple_to_flw": "Choisissez le nombre de comptes auxquels vous voulez vous abonner",
    "save_btn": "SAVE",
    "discard_btn": "DISCARD",
    "url_error_title": "Erreur d'URL",
    "url_error_desc1": "Vous avez oublié d'entrer l'URL",
    "url_error_desc2": "L'URL fournie ne correspond pas au format requis",
    "no_btn_sl_title": "Aucun bouton sélectionné",
    "no_btn_sl_desc": "Vous n'avez pas coché de bouton",
    "no_vintie": "Aucun Vintie à suivre",
    "no_valid_number": "Vous n'avez pas saisi un nombre de followers Vintie à suivre. Veuillez entrer un nombre valide et réessayer"
}, -->