# Form implementation generated from reading ui file 'connectionGoogle.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from tkinter import messagebox
from PyQt6 import QtCore, QtGui, QtWidgets
from engine import Email
from accueil import Ui_windowAccueil
from toolBar import setup_menubar


class Ui_ConnectionGoogle(object):

    def setupUi(self, primary):
        self.centralwidget = QtWidgets.QWidget(parent=primary.MainWindow)
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        spacerItem = QtWidgets.QSpacerItem(311, 153, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 2, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.password = QtWidgets.QLineEdit(parent=self.frame)
        self.gridLayout_3.addWidget(self.password, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 2, 1, 1, 1)
        self.email = QtWidgets.QLineEdit(parent=self.frame)
        self.gridLayout_3.addWidget(self.email, 0, 1, 1, 1)
        self.labelEnterPassword = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelEnterPassword.setFont(font)
        self.gridLayout_3.addWidget(self.labelEnterPassword, 1, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.submitConnect = QtWidgets.QPushButton(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.submitConnect.setFont(font)
        self.horizontalLayout_4.addWidget(self.submitConnect)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 3, 1, 1, 1)
        self.labelEnterEmail = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelEnterEmail.setFont(font)
        self.gridLayout_3.addWidget(self.labelEnterEmail, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 3, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(311, 156, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 4, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(304, 156, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 3, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(312, 156, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 3, 0, 1, 1)
        self.company = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(20)
        self.company.setFont(font)
        self.gridLayout_4.addWidget(self.company, 1, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_4.addItem(spacerItem7, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        primary.MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=primary.MainWindow)
        primary.MainWindow.setStatusBar(self.statusbar)

        # Mechanisms
        setup_menubar(self, primary)
        self.submitConnect.clicked.connect(lambda:self.google_connection(primary))
        
        self.retranslateUi(primary)
        QtCore.QMetaObject.connectSlotsByName(primary.MainWindow)

    def retranslateUi(self, primary):        
        self.company.setText("<html><head/><body><p align=\"center\"><span style=\" font-size:48pt; color:#4285f4;\">G</span><span style=\" font-size:48pt; color:#db4a39;\">O</span><span style=\" font-size:48pt; color:#f4b400;\">O</span><span style=\" font-size:48pt; color:#4285f4;\">G</span><span style=\" font-size:48pt; color:#008000;\">L</span><span style=\" font-size:48pt; color:#db4a39;\">E</span></p></body></html>")
        self.submitConnect.setText("  "+primary.lang_file.get_page_text("connections_page", "connection_btn")+"  ")
        self.labelEnterPassword.setText(primary.lang_file.get_page_text("connections_page", "pswd"))
        self.labelEnterEmail.setText(primary.lang_file.get_page_text("connections_page", "email"))

    def google_connection(self, primary):
        if self.email.text() == "":
            return messagebox.showwarning(primary.lang_file.get_page_text("connections_page", "co_error_title"), primary.lang_file.get_page_text("connections_page", "co_error_msg1")+" email"+primary.lang_file.get_page_text("connections_page", "co_error_msg2"))
        if self.password.text() == "":
            return messagebox.showwarning(primary.lang_file.get_page_text("connections_page", "co_error_title"), primary.lang_file.get_page_text("connections_page", "co_error_msg1")+" password"+primary.lang_file.get_page_text("connections_page", "co_error_msg2"))
        
        # connect the user to his account
        google_account = Email(self.email.text(), self.password.text(), primary)
        primary.log_account(google_account)
        Ui_windowAccueil().setupUi(primary)