# Form implementation generated from reading ui file 'FollowMass.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from tkinter import messagebox
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FollowMass(object):
    
    def setupUi(self, primary):
        self.centralwidget = QtWidgets.QWidget(parent=primary.MainWindow)
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.line_2 = QtWidgets.QFrame(parent=self.frame)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_2.setLineWidth(20)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.gridLayout_2.addWidget(self.line_2, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(parent=self.frame)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line.setLineWidth(20)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.gridLayout_2.addWidget(self.line, 0, 2, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 6, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_6.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_6.addItem(spacerItem2, 4, 1, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.Secreteritat = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.Secreteritat.setFont(font)
        self.Secreteritat.setStyleSheet("color: rgb(98, 98, 98);")
        self.horizontalLayout_11.addWidget(self.Secreteritat, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_6.addLayout(self.horizontalLayout_11, 1, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.my_reviews_btn = QtWidgets.QRadioButton(parent=self.frame)
        self.my_reviews_btn.setChecked(primary.param.get_dict()["my-rw-btn-checked"])
        font = QtGui.QFont()
        font.setPointSize(12)
        self.my_reviews_btn.setFont(font)
        self.gridLayout_7.addWidget(self.my_reviews_btn, 1, 0, 1, 1)
        self.tree_btn = QtWidgets.QRadioButton(parent=self.frame)
        self.tree_btn.setMinimumSize(QtCore.QSize(50, 0))
        self.tree_btn.setSizeIncrement(QtCore.QSize(50, 0))
        self.tree_btn.setChecked(primary.param.get_dict()["tree-btn-checked"])
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tree_btn.setFont(font)
        self.gridLayout_7.addWidget(self.tree_btn, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.textBrowser_4 = QtWidgets.QTextBrowser(parent=self.frame)
        self.textBrowser_4.setMinimumSize(QtCore.QSize(200, 150))
        self.textBrowser_4.setMaximumSize(QtCore.QSize(250, 150))
        self.textBrowser_4.setSizeIncrement(QtCore.QSize(250, 100))
        self.textBrowser_4.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.textBrowser_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.gridLayout_3.addWidget(self.textBrowser_4, 0, 1, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(parent=self.frame)
        self.spinBox_2.setMinimumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setMaximum(10000)
        self.spinBox_2.setSingleStep(10)        
        self.spinBox_2.setValue(primary.param.get_dict()["sp-val"])
        self.gridLayout_3.addWidget(self.spinBox_2, 1, 0, 1, 1)
        self.textBrowser_6 = QtWidgets.QTextBrowser(parent=self.frame)
        self.textBrowser_6.setMinimumSize(QtCore.QSize(200, 80))
        self.textBrowser_6.setMaximumSize(QtCore.QSize(250, 80))
        self.textBrowser_6.setSizeIncrement(QtCore.QSize(250, 100))
        self.textBrowser_6.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.textBrowser_6.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.gridLayout_3.addWidget(self.textBrowser_6, 1, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 3, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.save_btn = QtWidgets.QPushButton(parent=self.frame)
        self.save_btn.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.save_btn.setFont(font)
        self.save_btn.setStyleSheet("background-color: rgb(22, 198, 12);")
        self.save_btn.setAutoDefault(False)
        self.save_btn.setDefault(True)
        self.save_btn.setFlat(True)
        self.horizontalLayout_8.addWidget(self.save_btn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.discard_btn = QtWidgets.QPushButton(parent=self.frame)
        self.discard_btn.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.discard_btn.setFont(font)
        self.discard_btn.setStyleSheet("background-color: rgb(232, 18, 36);")
        self.discard_btn.setAutoDefault(False)
        self.discard_btn.setDefault(True)
        self.discard_btn.setFlat(True)
        self.horizontalLayout_8.addWidget(self.discard_btn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.gridLayout_6.addLayout(self.horizontalLayout_8, 5, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_6.addItem(spacerItem6, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_6, 0, 6, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_5.addItem(spacerItem7, 6, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_5.addItem(spacerItem8, 2, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_5.addItem(spacerItem9, 4, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.AdManagement = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.AdManagement.setFont(font)
        self.AdManagement.setStyleSheet("color: rgb(98, 98, 98);")
        self.horizontalLayout_9.addWidget(self.AdManagement, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_5.addLayout(self.horizontalLayout_9, 1, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setMinimumSize(QtCore.QSize(0, 36))
        self.label.setMaximumSize(QtCore.QSize(20, 16777215))
        self.horizontalLayout_7.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.horizontalLayout_7.addWidget(self.lineEdit)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.scrap_btn = QtWidgets.QPushButton(parent=self.frame)
        self.scrap_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.scrap_btn.setFont(font)
        self.scrap_btn.setStyleSheet("background-color: rgb(244, 81, 0);")
        self.scrap_btn.setAutoDefault(False)
        self.scrap_btn.setDefault(True)
        self.scrap_btn.setFlat(True)
        self.horizontalLayout_7.addWidget(self.scrap_btn)
        self.gridLayout_5.addLayout(self.horizontalLayout_7, 5, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_5.addItem(spacerItem12, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.followings_btn = QtWidgets.QRadioButton(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.followings_btn.setFont(font)
        self.verticalLayout_2.addWidget(self.followings_btn)
        self.followers_btn = QtWidgets.QRadioButton(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.followers_btn.setFont(font)
        self.verticalLayout_2.addWidget(self.followers_btn)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.textBrowser_3 = QtWidgets.QTextBrowser(parent=self.frame)
        self.textBrowser_3.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.textBrowser_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.textBrowser_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.horizontalLayout_2.addWidget(self.textBrowser_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.frame)
        self.textBrowser.setMinimumSize(QtCore.QSize(300, 0))
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textBrowser.setSizeIncrement(QtCore.QSize(300, 0))
        self.textBrowser.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.verticalLayout.addWidget(self.textBrowser)
        self.gridLayout_5.addLayout(self.verticalLayout, 3, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.FollowMass = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.FollowMass.setFont(font)
        self.FollowMass.setMouseTracking(False)
        self.FollowMass.setStyleSheet("color: rgb(98, 98, 98);")
        self.horizontalLayout_10.addWidget(self.FollowMass, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_4.addLayout(self.horizontalLayout_10, 1, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_4.addItem(spacerItem13, 0, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem14)
        self.follow_btn = QtWidgets.QPushButton(parent=self.frame)
        self.follow_btn.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.follow_btn.setFont(font)
        self.follow_btn.setStyleSheet("background-color: rgb(71, 212, 212);")
        self.follow_btn.setAutoDefault(False)
        self.follow_btn.setDefault(True)
        self.follow_btn.setFlat(True)
        self.horizontalLayout_6.addWidget(self.follow_btn)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem15)
        self.recover_btn = QtWidgets.QPushButton(parent=self.frame)
        self.recover_btn.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.recover_btn.setFont(font)
        self.recover_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.recover_btn.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.recover_btn.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.recover_btn.setAcceptDrops(False)
        self.recover_btn.setToolTipDuration(-1)
        self.recover_btn.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.recover_btn.setAutoFillBackground(False)
        self.recover_btn.setStyleSheet("background-color: rgb(157, 79, 236);")
        self.recover_btn.setAutoDefault(False)
        self.recover_btn.setDefault(True)
        self.recover_btn.setFlat(True)
        self.horizontalLayout_6.addWidget(self.recover_btn)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem16)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 5, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_4.addItem(spacerItem17, 4, 1, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_4.addItem(spacerItem18, 2, 1, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_4.addItem(spacerItem19, 6, 1, 1, 1)
        self.textBrowser_2 = QtWidgets.QTextBrowser(parent=self.frame)
        self.textBrowser_2.setMinimumSize(QtCore.QSize(300, 250))
        self.textBrowser_2.setSizeIncrement(QtCore.QSize(300, 0))
        self.textBrowser_2.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"")
        self.textBrowser_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.gridLayout_4.addWidget(self.textBrowser_2, 3, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_4)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 3, 1, 1)
        self.line_4 = QtWidgets.QFrame(parent=self.frame)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_4.setLineWidth(20)
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.gridLayout_2.addWidget(self.line_4, 0, 7, 1, 1)
        self.line_3 = QtWidgets.QFrame(parent=self.frame)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_3.setLineWidth(1)
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.gridLayout_2.addWidget(self.line_3, 0, 5, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        primary.MainWindow.setCentralWidget(self.centralwidget)

        # Mechanisms
        self.scrap_btn.clicked.connect(lambda:self.scrap_vintie(primary))
        self.follow_btn.clicked.connect(lambda:self.follow_mass(primary))
        self.recover_btn.clicked.connect(lambda:self.recover_followed_users(primary))
        self.discard_btn.clicked.connect(lambda:self.discard())
        self.save_btn.clicked.connect(lambda:self.save(primary))

        self.retranslateUi(primary)
        QtCore.QMetaObject.connectSlotsByName(primary.MainWindow)

    def retranslateUi(self, primary):
        self.Secreteritat.setText("⚙ " + primary.lang_file.get_page_text("follow_mass_page", "settings_title"))
        self.my_reviews_btn.setText(primary.lang_file.get_page_text("follow_mass_page", "my_reviews_btn"))
        self.tree_btn.setText(primary.lang_file.get_page_text("follow_mass_page", "tree_btn"))
        tree_desc = primary.lang_file.get_page_text("follow_mass_page", "tree_desc")
        my_reviews_desc = primary.lang_file.get_page_text("follow_mass_page", "my_reviews_desc")
        self.textBrowser_4.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:12pt;\">🌳</span><span style=\" font-family:\'Segoe UI\'; font-size:9pt;\"> {tree_desc}</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Segoe UI\'; font-size:9pt;\"><br /></p>\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:12pt;\">📝</span><span style=\" font-family:\'Segoe UI\'; font-size:9pt;\"> {my_reviews_desc}</span></p></body></html>")
        nb_ple_to_flw = primary.lang_file.get_page_text("follow_mass_page", "nb_ple_to_flw")
        self.textBrowser_6.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:12pt;\">🎲</span><span style=\" font-family:\'Segoe UI\'; font-size:9pt;\"> {nb_ple_to_flw}</span></p></body></html>")
        self.save_btn.setText(primary.lang_file.get_page_text("follow_mass_page", "save_btn") + " ✅")
        self.discard_btn.setText(primary.lang_file.get_page_text("follow_mass_page", "discard_btn") + " 🟥")
        self.AdManagement.setText("🕵️‍ " + primary.lang_file.get_page_text("follow_mass_page", "vintie_followers_title"))
        self.label.setText("URL")
        self.scrap_btn.setText(primary.lang_file.get_page_text("follow_mass_page", "scrap_btn") + " 👊")
        self.followings_btn.setText(primary.lang_file.get_page_text("follow_mass_page", "followings"))
        self.followers_btn.setText(primary.lang_file.get_page_text("follow_mass_page", "followers"))
        folowings_desc = primary.lang_file.get_page_text("follow_mass_page", "folowings_desc")
        followers_desc = primary.lang_file.get_page_text("follow_mass_page", "followers_desc")
        self.textBrowser_3.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Segoe UI\'; font-size:9pt;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Segoe UI\'; font-size:12pt;\"><br /></p>\n"
f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:12pt;\">🥏</span><span style=\" font-family:\'Segoe UI\'; font-size:9pt;\"> {folowings_desc}</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Segoe UI\'; font-size:9pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Segoe UI\'; font-size:9pt;\"><br /></p>\n"
f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:12pt;\">🕸</span><span style=\" font-family:\'Segoe UI\'; font-size:9pt;\"> {followers_desc}</span></p></body></html>")
        url_entry_desc = primary.lang_file.get_page_text("follow_mass_page", "url_entry_desc")
        self.textBrowser.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:12pt;\">🔗</span><span style=\" font-family:\'Segoe UI\'; font-size:9pt;\"> {url_entry_desc}</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Segoe UI\'; font-size:9pt;\"><br /></p></body></html>")
        self.FollowMass.setText(primary.lang_file.get_page_text("follow_mass_page", "follow_title") + " 📈 - 📉 " + primary.lang_file.get_page_text("follow_mass_page", "unfollow_title"))
        self.follow_btn.setText(primary.lang_file.get_page_text("follow_mass_page", "follow_btn") + " ⚡")
        self.recover_btn.setText(primary.lang_file.get_page_text("follow_mass_page", "recover_btn") + " 🔙")
        desc_1 = primary.lang_file.get_page_text("follow_mass_page", "desc_1")
        desc_2 = primary.lang_file.get_page_text("follow_mass_page", "desc_2")
        self.textBrowser_2.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Segoe UI\'; font-size:9pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Segoe UI\'; font-size:9pt;\"><br /></p>\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:12pt;\">🌟</span><span style=\" font-family:\'Segoe UI\'; font-size:9pt;\"> {desc_1}</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Segoe UI\'; font-size:9pt;\"><br /></p>\n"
f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:12pt;\">❌</span><span style=\" font-family:\'Segoe UI\'; font-size:9pt;\"> {desc_2}</span></p></body></html>")

    def scrap_vintie(self, primary):
        """Scraps a vintie using its URL"""
        try:
            if primary.vinted_api.inform_status_connection() == False:
                return
            url = self.lineEdit.text()
            if url == "":
                messagebox.showwarning(primary.lang_file.get_page_text("follow_mass_page", "url_error_title"), primary.lang_file.get_page_text("follow_mass_page", "url_error_desc1"))
                return
            if not "https://www.vinted." in url:
                messagebox.showinfo(primary.lang_file.get_page_text("follow_mass_page", "url_error_title"), primary.lang_file.get_page_text("follow_mass_page", "url_error_desc2"))
                return
            if self.followings_btn.isChecked():
                primary.vinted_api.scrap_following_from(url)
            elif self.followers_btn.isChecked():
                primary.vinted_api.scrap_followers_from(url)
            else:
                messagebox.showwarning(primary.lang_file.get_page_text("follow_mass_page", "no_btn_sl_title"), primary.lang_file.get_page_text("follow_mass_page", "no_btn_sl_desc"))
        except:
            primary.not_co_vinted()
    
    def follow_mass(self, primary):
        if primary.not_co_vinted():
            return
        try:
            if self.tree_btn.isChecked():
                if self.spinBox_2.value() == 0:
                    messagebox.showinfo(primary.lang_file.get_page_text("follow_mass_page", "no_vintie"), primary.lang_file.get_page_text("follow_mass_page", "no_valid_number"))
                    return
                primary.vinted_api.follow_mass(self.spinBox_2.value())
            elif self.my_reviews_btn.isChecked():
                primary.vinted_api.follow_mass_my_reviews()
            else:
                messagebox.showwarning(primary.lang_file.get_page_text("follow_mass_page", "no_btn_sl_title"), primary.lang_file.get_page_text("follow_mass_page", "no_btn_sl_desc"))
        except:
            primary.vinted_api.token_expired()
    
    def recover_followed_users(self, primary):
        if primary.not_co_vinted():
            return
        try:
            primary.vinted_api.recover_followed_users()
        except:            
            primary.vinted_api.token_expired()

    def discard(self):
        """Resets the buttons of follow mass settings"""
        self.spinBox_2.setValue(0)

        if self.tree_btn.isChecked():
            self.my_reviews_btn.setChecked(True)
            self.tree_btn.setChecked(False)
        elif self.my_reviews_btn.isChecked():
            self.tree_btn.setChecked(True)
            self.my_reviews_btn.setChecked(False)

    def save(self, primary):
        """Saves the configuration of the button and the spin box"""
        primary.param.set_pref("sp-val", self.spinBox_2.value())
        primary.param.set_pref("my-rw-btn-checked", self.my_reviews_btn.isChecked())
        primary.param.set_pref("tree-btn-checked", self.tree_btn.isChecked())