# Form implementation generated from reading ui file 'Information.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_Information(object):
    
    def setupUi(self, primary):
        self.centralwidget = QtWidgets.QWidget(parent=primary.MainWindow)
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.about = QtWidgets.QTabWidget(parent=self.frame)
        self.tab = QtWidgets.QWidget()
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.tab)
        self.scrollArea.setMinimumSize(QtCore.QSize(940, 440))
        self.scrollArea.setMaximumSize(QtCore.QSize(940, 1000))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 940, 440))
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.scrollArea_2 = QtWidgets.QScrollArea(parent=self.scrollAreaWidgetContents)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -1230, 897, 2410))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.line_11 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_2)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_11.setLineWidth(2)
        self.line_11.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.verticalLayout_2.addWidget(self.line_11)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.textBrowser_3 = QtWidgets.QTextBrowser(parent=self.scrollAreaWidgetContents_2)
        self.textBrowser_3.setMinimumSize(QtCore.QSize(0, 180))
        self.textBrowser_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.horizontalLayout_2.addWidget(self.textBrowser_3)
        self.label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        self.label.setMinimumSize(QtCore.QSize(433, 180))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line_10 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_2)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_10.setLineWidth(2)
        self.line_10.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.verticalLayout_2.addWidget(self.line_10)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.textBrowser_4 = QtWidgets.QTextBrowser(parent=self.scrollAreaWidgetContents_2)
        self.textBrowser_4.setMinimumSize(QtCore.QSize(0, 225))
        self.textBrowser_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.horizontalLayout_3.addWidget(self.textBrowser_4)
        self.label_2 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        self.label_2.setMinimumSize(QtCore.QSize(433, 0))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.line_9 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_2)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_9.setLineWidth(2)
        self.line_9.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.verticalLayout_2.addWidget(self.line_9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.textBrowser_9 = QtWidgets.QTextBrowser(parent=self.scrollAreaWidgetContents_2)
        self.textBrowser_9.setMinimumSize(QtCore.QSize(0, 210))
        self.textBrowser_9.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.horizontalLayout_4.addWidget(self.textBrowser_9)
        self.label_3 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        self.label_3.setMinimumSize(QtCore.QSize(433, 0))
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.horizontalLayout_4.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_2)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.textBrowser_10 = QtWidgets.QTextBrowser(parent=self.scrollAreaWidgetContents_2)
        self.textBrowser_10.setMinimumSize(QtCore.QSize(0, 220))
        self.textBrowser_10.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.horizontalLayout_5.addWidget(self.textBrowser_10)
        self.label_4 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        self.label_4.setMinimumSize(QtCore.QSize(433, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.horizontalLayout_5.addWidget(self.label_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.line_2 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_2)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.textBrowser_5 = QtWidgets.QTextBrowser(parent=self.scrollAreaWidgetContents_2)
        self.textBrowser_5.setMinimumSize(QtCore.QSize(0, 180))
        self.textBrowser_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.horizontalLayout_6.addWidget(self.textBrowser_5)
        self.label_5 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        self.label_5.setMinimumSize(QtCore.QSize(433, 0))
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.horizontalLayout_6.addWidget(self.label_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.line_3 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_2)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.verticalLayout_2.addWidget(self.line_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.textBrowser_6 = QtWidgets.QTextBrowser(parent=self.scrollAreaWidgetContents_2)
        self.textBrowser_6.setMinimumSize(QtCore.QSize(0, 180))
        self.textBrowser_6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.horizontalLayout_7.addWidget(self.textBrowser_6)
        self.label_6 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        self.label_6.setMinimumSize(QtCore.QSize(433, 0))
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.horizontalLayout_7.addWidget(self.label_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.line_4 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_2)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.verticalLayout_2.addWidget(self.line_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.textBrowser_11 = QtWidgets.QTextBrowser(parent=self.scrollAreaWidgetContents_2)
        self.textBrowser_11.setMinimumSize(QtCore.QSize(0, 180))
        self.textBrowser_11.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser_11.setObjectName("textBrowser_11")
        self.horizontalLayout_8.addWidget(self.textBrowser_11)
        self.label_7 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        self.label_7.setMinimumSize(QtCore.QSize(433, 0))
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.line_5 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_2)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_2.addWidget(self.line_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.textBrowser_12 = QtWidgets.QTextBrowser(parent=self.scrollAreaWidgetContents_2)
        self.textBrowser_12.setMinimumSize(QtCore.QSize(0, 180))
        self.textBrowser_12.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser_12.setObjectName("textBrowser_12")
        self.horizontalLayout_9.addWidget(self.textBrowser_12)
        self.label_9 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        self.label_9.setMinimumSize(QtCore.QSize(433, 0))
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.line_6 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_2)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_2.addWidget(self.line_6)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.textBrowser_13 = QtWidgets.QTextBrowser(parent=self.scrollAreaWidgetContents_2)
        self.textBrowser_13.setMinimumSize(QtCore.QSize(0, 330))
        self.textBrowser_13.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser_13.setObjectName("textBrowser_13")
        self.horizontalLayout_10.addWidget(self.textBrowser_13)
        self.label_10 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        self.label_10.setMinimumSize(QtCore.QSize(433, 0))
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.line_7 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_2)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_7.setLineWidth(2)
        self.line_7.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_2.addWidget(self.line_7)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.textBrowser_14 = QtWidgets.QTextBrowser(parent=self.scrollAreaWidgetContents_2)
        self.textBrowser_14.setMinimumSize(QtCore.QSize(0, 310))
        self.textBrowser_14.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser_14.setObjectName("textBrowser_14")
        self.horizontalLayout_11.addWidget(self.textBrowser_14)
        self.label_8 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        self.label_8.setMinimumSize(QtCore.QSize(433, 0))
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_11.addWidget(self.label_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.line_8 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_2)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_8.setLineWidth(2)
        self.line_8.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_2.addWidget(self.line_8)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_5.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.about.addTab(self.tab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.tab_5)
        self.textBrowser.setGeometry(QtCore.QRect(10, 20, 928, 416))
        self.textBrowser.setObjectName("textBrowser")
        self.about.addTab(self.tab_5, "")
        self.About = QtWidgets.QWidget()
        self.About.setObjectName("About")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.About)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.textBrowser_7 = QtWidgets.QTextBrowser(parent=self.About)
        self.textBrowser_7.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.gridLayout_11.addWidget(self.textBrowser_7, 0, 0, 1, 1)
        self.about.addTab(self.About, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.textBrowser_8 = QtWidgets.QTextBrowser(parent=self.tab_3)
        self.textBrowser_8.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.textBrowser_8.setOpenExternalLinks(True)
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.gridLayout_12.addWidget(self.textBrowser_8, 0, 0, 1, 1)
        self.about.addTab(self.tab_3, "")
        self.gridLayout_2.addWidget(self.about, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        primary.MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(primary)
        self.about.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(primary.MainWindow)

    def retranslateUi(self, primary):
        pictures_title = primary.lang_file.get_page_text("informations_page", "pictures_title")
        pictures_desc1 = primary.lang_file.get_page_text("informations_page", "pictures_desc1")
        pictures_desc2 = primary.lang_file.get_page_text("informations_page", "pictures_desc2")
        self.textBrowser_3.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">📷</span><span style=\" font-size:12pt;\"> {pictures_title}</span></p>\n"
f"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">{pictures_desc1}</span><span style=\" font-size:12pt;\">📸</span><span style=\" font-size:9pt;\">{pictures_desc2}</span><span style=\" font-size:12pt;\">🌟👕👖👗</span></p></body></html>")
        self.label.setText("PHOTO")
        clear_descriptions_title = primary.lang_file.get_page_text("informations_page", "clear_descriptions_title")
        clear_descriptions_desc1 = primary.lang_file.get_page_text("informations_page", "clear_descriptions_desc1")
        self.textBrowser_4.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">📝 {clear_descriptions_title}</span></p>\n"
f"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">{clear_descriptions_desc1}</span></p></body></html>")
        self.label_2.setText("PHOTO")
        follow_mass_title = primary.lang_file.get_page_text("informations_page", "follow_mass_title")
        follow_mass_desc1 = primary.lang_file.get_page_text("informations_page", "follow_mass_desc1")
        follow_mass_desc2 = primary.lang_file.get_page_text("informations_page", "follow_mass_desc2")
        self.textBrowser_9.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">{follow_mass_title}</span></p>\n"
f"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">{follow_mass_desc1}</span></p>\n"
f"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">{follow_mass_desc2}</span></p></body></html>")
        self.label_3.setText("PHOTO")
        thank_you_title = primary.lang_file.get_page_text("informations_page", "thank_you_title")
        thank_you_desc1 = primary.lang_file.get_page_text("informations_page", "thank_you_desc1")
        thank_you_desc2 = primary.lang_file.get_page_text("informations_page", "thank_you_desc2")
        self.textBrowser_10.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">{thank_you_title}</span></p>\n"
f"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">{thank_you_desc1}</span></p>\n"
f"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">{thank_you_desc2}</span></p></body></html>")
        self.label_4.setText("PHOTO")
        buy_printer_title = primary.lang_file.get_page_text("informations_page", "buy_printer_title")
        buy_printer_desc1 = primary.lang_file.get_page_text("informations_page", "buy_printer_desc1")
        self.textBrowser_5.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">{buy_printer_title}</span></p>\n"
f"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">{buy_printer_desc1}</span></p></body></html>")
        self.label_5.setText("PHOTO")
        free_scotch_title = primary.lang_file.get_page_text("informations_page", "free_scotch_title")
        free_scotch_desc1 = primary.lang_file.get_page_text("informations_page", "free_scotch_desc1")
        self.textBrowser_6.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">{free_scotch_title}</span></p>\n"
f"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">{free_scotch_desc1}</span></p></body></html>")
        self.label_6.setText("PHOTO")
        online_bank_title = primary.lang_file.get_page_text("informations_page", "online_bank_title")
        online_bank_desc1 = primary.lang_file.get_page_text("informations_page", "online_bank_desc1")
        self.textBrowser_11.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">{online_bank_title}</span></p>\n"
f"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">{online_bank_desc1}</span></p></body></html>")
        self.label_7.setText("PHOTO")
        small_warehouse_title = primary.lang_file.get_page_text("informations_page", "small_warehouse_title")
        small_warehouse_desc1 = primary.lang_file.get_page_text("informations_page", "small_warehouse_desc1")
        self.textBrowser_12.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">{small_warehouse_title}</span></p>\n"
f"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">{small_warehouse_desc1}</span></p></body></html>")
        self.label_9.setText("TextLabel")
        id_verif_as_pro_title = primary.lang_file.get_page_text("informations_page", "id_verif_as_pro_title")
        id_verif_as_pro_desc1 = primary.lang_file.get_page_text("informations_page", "id_verif_as_pro_desc1")
        id_verif_as_pro_desc2 = primary.lang_file.get_page_text("informations_page", "id_verif_as_pro_desc2")
        id_verif_as_pro_desc3 = primary.lang_file.get_page_text("informations_page", "id_verif_as_pro_desc3")
        id_verif_as_pro_desc4 = primary.lang_file.get_page_text("informations_page", "id_verif_as_pro_desc4")
        id_verif_as_pro_desc5 = primary.lang_file.get_page_text("informations_page", "id_verif_as_pro_desc5")
        id_verif_as_pro_desc6 = primary.lang_file.get_page_text("informations_page", "id_verif_as_pro_desc6")
        id_verif_as_pro_desc7 = primary.lang_file.get_page_text("informations_page", "id_verif_as_pro_desc7")
        self.textBrowser_13.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">{id_verif_as_pro_title}</span></p>\n"
f"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">{id_verif_as_pro_desc1}</span><span style=\" font-size:9pt; font-weight:600;\">{id_verif_as_pro_desc2}</span><span style=\" font-size:9pt;\">{id_verif_as_pro_desc3}</span><span style=\" font-size:9pt; font-weight:600;\">{id_verif_as_pro_desc4}</span><span style=\" font-size:9pt;\">{id_verif_as_pro_desc5}</span><span style=\" font-size:9pt; text-decoration: underline;\">{id_verif_as_pro_desc6}</span><span style=\" font-size:9pt;\">{id_verif_as_pro_desc7}</span><a href=\"https://data.inpi.fr\"><span style=\" font-size:9pt; text-decoration: underline; color:#0000ff;\">Inpi</span></a></p></body></html>")
        self.label_10.setText("PHOTO")
        avoid_ban_title = primary.lang_file.get_page_text("informations_page", "avoid_ban_title")
        avoid_ban_desc1 = primary.lang_file.get_page_text("informations_page", "avoid_ban_desc1")
        avoid_ban_desc2 = primary.lang_file.get_page_text("informations_page", "avoid_ban_desc2")
        avoid_ban_desc3 = primary.lang_file.get_page_text("informations_page", "avoid_ban_desc3")
        avoid_ban_desc4 = primary.lang_file.get_page_text("informations_page", "avoid_ban_desc4")
        avoid_ban_desc5 = primary.lang_file.get_page_text("informations_page", "avoid_ban_desc5")
        avoid_ban_desc6 = primary.lang_file.get_page_text("informations_page", "avoid_ban_desc6")
        self.textBrowser_14.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">{avoid_ban_title}</span></p>\n"
f"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">{avoid_ban_desc1}</span></p>\n"
f"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">{avoid_ban_desc2}</span><span style=\" font-size:9pt; font-weight:600;\">{avoid_ban_desc3}</span><span style=\" font-size:9pt;\">{avoid_ban_desc4}</span><span style=\" font-size:9pt; font-weight:600;\">{avoid_ban_desc5}</span><span style=\" font-size:9pt;\">{avoid_ban_desc6}</span></p></body></html>")
        self.label_8.setText("PHOTO")
        self.about.setTabText(self.about.indexOf(self.tab), primary.lang_file.get_page_text("informations_page", "tricks"))
        overview_title = primary.lang_file.get_page_text("informations_page", "overview_title")
        overview_work_title = primary.lang_file.get_page_text("informations_page", "overview_work_title")
        overview_work_desc1 = primary.lang_file.get_page_text("informations_page", "overview_work_desc1")
        overview_work_desc2 = primary.lang_file.get_page_text("informations_page", "overview_work_desc2")
        overview_work_desc3 = primary.lang_file.get_page_text("informations_page", "overview_work_desc3")
        overview_work_desc4 = primary.lang_file.get_page_text("informations_page", "overview_work_desc4")
        overview_work_desc5 = primary.lang_file.get_page_text("informations_page", "overview_work_desc5")
        self.textBrowser.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">{overview_title}</span></p>\n"
f"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">⚠️    {overview_work_title}</span></p>\n"
f"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">{overview_work_desc1}</span></p>\n"
f"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">🚀    {overview_work_desc2}</span></p>\n"
f"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">{overview_work_desc3}</span></p>\n"
f"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">🔑    {overview_work_desc4}</span></p>\n"
f"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">{overview_work_desc5}</span></p></body></html>")
        self.about.setTabText(self.about.indexOf(self.tab_5), primary.lang_file.get_page_text("informations_page", "overview"))
        overview_story_title = primary.lang_file.get_page_text("informations_page", "overview_story_title")
        overview_story_desc1 = primary.lang_file.get_page_text("informations_page", "overview_story_desc1")
        overview_story_desc2 = primary.lang_file.get_page_text("informations_page", "overview_story_desc2")
        overview_story_desc3 = primary.lang_file.get_page_text("informations_page", "overview_story_desc3")
        overview_story_desc4 = primary.lang_file.get_page_text("informations_page", "overview_story_desc4")
        overview_story_desc5 = primary.lang_file.get_page_text("informations_page", "overview_story_desc5")
        self.textBrowser_7.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">{overview_story_title}</span></p>\n"
f"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\">    </span><span style=\" font-size:10pt;\">{overview_story_desc1}</span></p>\n"
f"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\">    </span><span style=\" font-size:10pt;\">{overview_story_desc2}</span></p>\n"
f"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt;\">    </span><span style=\" font-size:10pt;\">{overview_story_desc3}</span><span style=\" font-size:10pt; font-weight:600;\">{overview_story_desc4}</span><span style=\" font-size:10pt;\"> 💼.</span></p>\n"
f"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">{overview_story_desc5}</span></p></body></html>")
        self.about.setTabText(self.about.indexOf(self.About), primary.lang_file.get_page_text("informations_page", "our_story"))
        affiliation_title = primary.lang_file.get_page_text("informations_page", "affiliation_title")
        affiliation_coupert_desc1 = primary.lang_file.get_page_text("informations_page", "affiliation_coupert_desc1")
        affiliation_coupert_desc2 = primary.lang_file.get_page_text("informations_page", "affiliation_coupert_desc2")
        affiliation_coupert_desc3 = primary.lang_file.get_page_text("informations_page", "affiliation_coupert_desc3")
        affiliation_ali_desc1 = primary.lang_file.get_page_text("informations_page", "affiliation_ali_desc1")
        affiliation_ali_desc2 = primary.lang_file.get_page_text("informations_page", "affiliation_ali_desc2")
        affiliation_ali_desc3 = primary.lang_file.get_page_text("informations_page", "affiliation_ali_desc3")
        affiliation_boursorama_desc0 = primary.lang_file.get_page_text("informations_page", "affiliation_boursorama_desc0")
        affiliation_boursorama_desc1 = primary.lang_file.get_page_text("informations_page", "affiliation_boursorama_desc1")
        affiliation_boursorama_desc2 = primary.lang_file.get_page_text("informations_page", "affiliation_boursorama_desc2")
        affiliation_boursorama_desc3 = primary.lang_file.get_page_text("informations_page", "affiliation_boursorama_desc3")
        affiliation_boursorama_desc4 = primary.lang_file.get_page_text("informations_page", "affiliation_boursorama_desc4")
        cliquable_link = primary.lang_file.get_page_text("informations_page", "cliquable_link")
        self.textBrowser_8.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
f"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">{affiliation_title}</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Segoe UI\'; font-size:8pt;\"><br /></p>\n"
f"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Coupert</span><span style=\" font-size:12pt;\"> 💰</span><span style=\" font-size:9pt;\">        </span><a href=\"https://www.coupert.com/invite/9uv4mpkda \"><span style=\" font-size:9pt; text-decoration: underline; color:#0000ff;\">{cliquable_link}</span></a></p>\n"
f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">{affiliation_coupert_desc1}</span></p>\n"
f"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">{affiliation_coupert_desc2}</span></p>\n"
f"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">{affiliation_coupert_desc3}</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
f"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">AliExpress</span><span style=\" font-size:12pt;\"> 🌍</span><span style=\" font-size:9pt;\">    </span><a href=\"https://a.aliexpress.com/_mthSH3K\"><span style=\" font-size:9pt; text-decoration: underline; color:#0000ff;\">{cliquable_link}</span></a></p>\n"
f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">{affiliation_ali_desc1}</span></p>\n"
f"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">{affiliation_ali_desc2}</span></p>\n"
f"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">{affiliation_ali_desc3}</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
f"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Boursorama 💼</span><span style=\" font-size:9pt;\">    </span><a href=\"https://bour.so/FHnn31mt9L\"><span style=\" font-size:9pt; text-decoration: underline; color:#0000ff;\">{cliquable_link}</span></a><span style=\" font-family:\'Segoe UI\'; font-size:9pt;\">{affiliation_boursorama_desc0}AURO2755</span></p>\n"
f"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">{affiliation_boursorama_desc1}</span></p>\n"
f"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">{affiliation_boursorama_desc2}</span></p>\n"
f"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">{affiliation_boursorama_desc3}</span></p>\n"
f"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">{affiliation_boursorama_desc4}</span></p></body></html>")
        self.about.setTabText(self.about.indexOf(self.tab_3), primary.lang_file.get_page_text("informations_page", "affiliation"))