# Form implementation generated from reading ui file 'Secreteriat.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from time import sleep
from tkinter import messagebox
from PyQt6 import QtCore, QtGui, QtWidgets
from setMailManagement import Ui_SetMailManagement
from toolBar import setup_menubar


class Ui_windowSecreteriat(object):
    
    def setupUi(self, primary):
        self.centralwidget = QtWidgets.QWidget(parent=primary.MainWindow)
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.line_8 = QtWidgets.QFrame(parent=self.frame_2)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_8.setLineWidth(20)
        self.line_8.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.gridLayout_3.addWidget(self.line_8, 0, 10, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.gridLayout_7 = QtWidgets.QGridLayout()
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_7.addItem(spacerItem, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_7.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_7.addItem(spacerItem2, 4, 1, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.getLabels_2 = QtWidgets.QPushButton(parent=self.frame_2)
        self.getLabels_2.setMinimumSize(QtCore.QSize(100, 0))
        self.getLabels_2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.getLabels_2.setFont(font)
        self.getLabels_2.setStyleSheet("background-color: rgb(22, 175, 12);")
        self.getLabels_2.setAutoDefault(False)
        self.getLabels_2.setDefault(True)
        self.getLabels_2.setFlat(True)
        self.horizontalLayout_12.addWidget(self.getLabels_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.goSetMailManagement = QtWidgets.QPushButton(parent=self.frame_2)
        self.goSetMailManagement.setMinimumSize(QtCore.QSize(100, 0))
        self.goSetMailManagement.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.goSetMailManagement.setFont(font)
        self.goSetMailManagement.setStyleSheet("background-color: rgb(170, 170, 170);")
        self.goSetMailManagement.setAutoDefault(False)
        self.goSetMailManagement.setDefault(True)
        self.goSetMailManagement.setFlat(True)
        self.goSetMailManagement.clicked.connect(lambda:Ui_SetMailManagement().setupUi(primary))
        self.horizontalLayout_12.addWidget(self.goSetMailManagement)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem5)
        self.gridLayout_7.addLayout(self.horizontalLayout_12, 5, 1, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.labelGetLabels_2 = QtWidgets.QLabel(parent=self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(19)
        font.setBold(True)
        self.labelGetLabels_2.setFont(font)
        self.labelGetLabels_2.setMouseTracking(False)
        self.labelGetLabels_2.setStyleSheet("color: rgb(179, 139, 109);")
        self.getLabels_2.clicked.connect(lambda:self.refresh_mails(primary))
        self.horizontalLayout_13.addWidget(self.labelGetLabels_2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem7)
        self.gridLayout_7.addLayout(self.horizontalLayout_13, 1, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_7.addItem(spacerItem8, 6, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.line = QtWidgets.QFrame(parent=self.frame_2)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.gridLayout_2.addWidget(self.line, 0, 1, 1, 1)
        self.textBrowser_2 = QtWidgets.QTextBrowser(parent=self.frame_2)
        self.textBrowser_2.setMinimumSize(QtCore.QSize(300, 250))
        self.textBrowser_2.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.textBrowser_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.gridLayout_2.addWidget(self.textBrowser_2, 0, 2, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.frame_2)
        self.textBrowser.setMinimumSize(QtCore.QSize(300, 250))
        self.textBrowser.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.gridLayout_2.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_2, 3, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_7)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 3, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_8.addItem(spacerItem9, 6, 1, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem10)
        self.goMailManagement_2 = QtWidgets.QPushButton(parent=self.frame_2)
        self.goMailManagement_2.setMinimumSize(QtCore.QSize(100, 0))
        self.goMailManagement_2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.goMailManagement_2.setFont(font)
        self.goMailManagement_2.setStyleSheet("background-color: rgb(219, 74, 57);")
        self.goMailManagement_2.setDefault(True)
        self.goMailManagement_2.setFlat(True)
        self.goMailManagement_2.clicked.connect(lambda:self.clear_conversations(primary))
        self.horizontalLayout_15.addWidget(self.goMailManagement_2)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem11)
        self.numbers_months = QtWidgets.QSpinBox(parent=self.frame_2)
        self.numbers_months.setMinimumSize(QtCore.QSize(50, 36))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.numbers_months.setFont(font)
        self.numbers_months.setMinimum(1)
        self.numbers_months.setMaximum(12)
        self.numbers_months.setProperty("value", 2)
        self.horizontalLayout_15.addWidget(self.numbers_months)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem12)
        self.gridLayout_8.addLayout(self.horizontalLayout_15, 5, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_8.addItem(spacerItem13, 4, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_8.addItem(spacerItem14, 0, 1, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem15)
        self.labelMailManagement_2 = QtWidgets.QLabel(parent=self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        self.labelMailManagement_2.setFont(font)
        self.labelMailManagement_2.setStyleSheet("color: rgb(179, 139, 109);")
        self.horizontalLayout_14.addWidget(self.labelMailManagement_2)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem16)
        self.gridLayout_8.addLayout(self.horizontalLayout_14, 1, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_8.addItem(spacerItem17, 2, 1, 1, 1)
        self.textBrowser_3 = QtWidgets.QTextBrowser(parent=self.frame_2)
        self.textBrowser_3.setMinimumSize(QtCore.QSize(300, 250))
        self.textBrowser_3.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.textBrowser_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.gridLayout_8.addWidget(self.textBrowser_3, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_8, 0, 9, 1, 1)
        self.line_6 = QtWidgets.QFrame(parent=self.frame_2)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_6.setLineWidth(20)
        self.line_6.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.gridLayout_3.addWidget(self.line_6, 0, 7, 1, 1)
        self.line_7 = QtWidgets.QFrame(parent=self.frame_2)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_7.setLineWidth(20)
        self.line_7.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.gridLayout_3.addWidget(self.line_7, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.frame_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        primary.MainWindow.setCentralWidget(self.centralwidget)
        
        # load the menubar and the toolbar
        setup_menubar(self, primary)
        # mechanisms
        self.retranslateUi(primary)
        QtCore.QMetaObject.connectSlotsByName(primary.MainWindow)

    def retranslateUi(self, primary):        
        self.getLabels_2.setText(primary.lang_file.get_page_text("seretariat_page", "process_mails_btn1")+" 🖨")
        self.goSetMailManagement.setText(primary.lang_file.get_page_text("seretariat_page", "process_mails_btn2")+" ⚙")
        self.labelGetLabels_2.setText("📪 "+primary.lang_file.get_page_text("seretariat_page", "process_mails_title"))
        # left text        
        self.textBrowser_2.setHtml(primary.lang_file.get_page_text("seretariat_page", "process_mails_descL"))
        # rifght text
        self.textBrowser.setHtml(primary.lang_file.get_page_text("seretariat_page", "process_mails_descR"))
        self.goMailManagement_2.setText(primary.lang_file.get_page_text("seretariat_page", "del_conv_btn")+" 📭")
        self.labelMailManagement_2.setText("📧 "+primary.lang_file.get_page_text("seretariat_page", "del_conv_title"))
        self.textBrowser_3.setHtml(primary.lang_file.get_page_text("seretariat_page", "del_conv_desc"))

    def refresh_mails(self, primary):
        """Starts the function refresh_emails from engine"""
        try:
            if not primary.is_connected():
                messagebox.showwarning(
                    primary.lang_file.get_pop_up_text("vinted_connection_error_title"),
                    primary.lang_file.get_pop_up_text("vinted_connection_error_desc")
                )
            elif not primary.is_connected("G"):
                messagebox.showwarning(
                    primary.lang_file.get_pop_up_text("google_connection_error_title"),
                    primary.lang_file.get_pop_up_text("google_connection_error_desc")
                )
            else:
                primary.google_account.refresh_emails()
                sleep(3) # delay estimated to get a mail
                primary.google_account.refresh_emails()
        except:
            primary.vinted_api.token_expired()

    def clear_conversations(self, primary):
        """Deletes old conversations. Close a tab to stop the execution"""
        if primary.not_co_vinted():
            return
        try:
            primary.vinted_api.clear_conversations(self.numbers_months.value())
        except:
            primary.vinted_api.token_expired()